// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DgUzSHszi-u9iD6e50GIfAWyfK_nnfs',
    appId: '1:718786358148:web:37c93b5e2d1270955ccbd1',
    messagingSenderId: '718786358148',
    projectId: 'shift-bookk',
    authDomain: 'shift-bookk.firebaseapp.com',
    storageBucket: 'shift-bookk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNdOX7-Pt-H21kOi0ADmbv0joYEhEXuM',
    appId: '1:718786358148:android:f8c583be0f9bf7d45ccbd1',
    messagingSenderId: '718786358148',
    projectId: 'shift-bookk',
    storageBucket: 'shift-bookk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEaVbZFAmeu3orEPAPpnvT6d228M354Uo',
    appId: '1:718786358148:ios:95423d622391bbc85ccbd1',
    messagingSenderId: '718786358148',
    projectId: 'shift-bookk',
    storageBucket: 'shift-bookk.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEaVbZFAmeu3orEPAPpnvT6d228M354Uo',
    appId: '1:718786358148:ios:95423d622391bbc85ccbd1',
    messagingSenderId: '718786358148',
    projectId: 'shift-bookk',
    storageBucket: 'shift-bookk.firebasestorage.app',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2DgUzSHszi-u9iD6e50GIfAWyfK_nnfs',
    appId: '1:718786358148:web:88353798a657d8815ccbd1',
    messagingSenderId: '718786358148',
    projectId: 'shift-bookk',
    authDomain: 'shift-bookk.firebaseapp.com',
    storageBucket: 'shift-bookk.firebasestorage.app',
  );
}
